version: "3.7"
volumes:
  notes-app-node_modules:
  weather-app-node_modules:
  web-server-node_modules:
  task-app-node_modules:
  data-node:
services:

  # node apps
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-test
    env_file:
      - .env
    image: node-test
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - notes-app-node_modules:/app/notes-app/node_modules
      - weather-app-node_modules:/app/weather-app/node_modules
      - web-server-node_modules:/app/web-server/node_modules
      - task-app-node_modules:/app/task-app/node_modules
    tty: true
    depends_on:
      - db
  
  # db
  db:
    image: mongo
    container_name: mongodb
    volumes:
        - data-node:/data/db
    ports:
        - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root