version: "3.7"
volumes:
  notes-app-node_modules:
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-test
    image: node-test
    ports:
      - 8080:8080
      - 9229:9229
    volumes:
      - .:/app
      - notes-app-node_modules:/app/notes-app/node_modules
    tty: true